#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Sat Mar 23 17:01:16 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class FrameDescuento(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrameDescuento.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_porcentaje = wx.StaticText(self.panel_1, -1, "Porcentaje")
        self.texto_porcentaje = wx.TextCtrl(self.panel_1, -1, "")
        self.panel_2 = wx.Panel(self, -1)
        self.boton_cancelar = wx.Button(self.panel_2, -1, "Cancelar")
        self.boton_aceptar = wx.Button(self.panel_2, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FrameDescuento.__set_properties
        self.SetTitle("frame_1")
        self.label_porcentaje.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.texto_porcentaje.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.boton_cancelar.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FrameDescuento.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_9 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_8 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_8.Add(self.label_porcentaje, 0, wx.ALL, 8)
        grid_sizer_8.Add(self.texto_porcentaje, 0, wx.RIGHT | wx.TOP | wx.BOTTOM, 8)
        self.panel_1.SetSizer(grid_sizer_8)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_9.Add(self.boton_cancelar, 0, wx.ALL, 5)
        grid_sizer_9.Add(self.boton_aceptar, 0, wx.ALL, 5)
        self.panel_2.SetSizer(grid_sizer_9)
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class FrameDescuento
class DescuentoFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class DescuentoFrame
if __name__ == "__main__":
    Frame_D = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = DescuentoFrame(None, -1, "")
    Frame_D.SetTopWindow(frame_1)
    frame_1.Show()
    Frame_D.MainLoop()
