#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Thu Mar 14 17:01:31 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Archivo")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Editar")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Ver")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Ayuda")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.panel_1 = wx.Panel(self, -1)
        self.btn_detalle_prendas = wx.Notebook(self.panel_1, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.btn_detalle_prendas, -1)
        self.texto_buscar_prendas = wx.TextCtrl(self.notebook_1_pane_1, -1, "Buscar...")
        self.radio_btn_1 = wx.RadioButton(self.notebook_1_pane_1, -1, "Codigo", style=wx.RB_GROUP)
        self.radio_btn_2 = wx.RadioButton(self.notebook_1_pane_1, -1, "Nombre", style=wx.RB_GROUP)
        self.lista_prendas = wx.ListCtrl(self.notebook_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "&Detalle")
        self.btn_eliminar_prendas = wx.Button(self.notebook_1_pane_1, -1, "&Eliminar")
        self.btn_nuevo_prendas = wx.Button(self.notebook_1_pane_1, -1, "&Nuevo")
        self.button_5 = wx.Button(self.notebook_1_pane_1, -1, "Realizar &Venta")
        self.notebook_1_pane_2 = wx.Panel(self.btn_detalle_prendas, -1)
        self.texto_buscar_clientes = wx.TextCtrl(self.notebook_1_pane_2, -1, "Buscar...")
        self.radio_btn_1_copy = wx.RadioButton(self.notebook_1_pane_2, -1, "DNI", style=wx.RB_GROUP)
        self.radio_btn_2_copy = wx.RadioButton(self.notebook_1_pane_2, -1, "Nombre", style=wx.RB_GROUP)
        self.lista_clientes = wx.ListCtrl(self.notebook_1_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.btn_detalle_clientes = wx.Button(self.notebook_1_pane_2, -1, "&Detalle")
        self.btn_eliminar_clientes = wx.Button(self.notebook_1_pane_2, -1, "&Eliminar")
        self.btn_nuevo_clientes = wx.Button(self.notebook_1_pane_2, -1, "&Nuevo")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Dress")
        self.SetSize((803, 500))
        self.SetFocus()
        self.texto_buscar_prendas.SetMinSize((250, 22))
        self.button_1.SetDefault()
        self.texto_buscar_clientes.SetMinSize((250, 22))
        self.btn_detalle_clientes.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_6_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_4_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.texto_buscar_prendas, 0, wx.ALL|wx.ADJUST_MINSIZE, 10)
        sizer_5.Add(self.radio_btn_1, 0, wx.RIGHT|wx.EXPAND|wx.ADJUST_MINSIZE, 20)
        sizer_5.Add(self.radio_btn_2, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_5, 1, wx.LEFT|wx.EXPAND, 20)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_6.Add(self.lista_prendas, 1, wx.LEFT|wx.RIGHT|wx.EXPAND|wx.ALIGN_RIGHT, 10)
        sizer_7.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.btn_eliminar_prendas, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.btn_nuevo_prendas, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(sizer_7, 0, wx.RIGHT, 10)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_8.Add(self.button_5, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 10)
        sizer_3.Add(sizer_8, 0, wx.ALIGN_RIGHT, 0)
        self.notebook_1_pane_1.SetSizer(sizer_3)
        sizer_4_copy.Add(self.texto_buscar_clientes, 0, wx.ALL|wx.ADJUST_MINSIZE, 10)
        sizer_5_copy.Add(self.radio_btn_1_copy, 0, wx.RIGHT|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ADJUST_MINSIZE, 20)
        sizer_5_copy.Add(self.radio_btn_2_copy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_4_copy.Add(sizer_5_copy, 1, wx.LEFT|wx.EXPAND, 20)
        sizer_3_copy.Add(sizer_4_copy, 0, wx.EXPAND, 0)
        sizer_6_copy.Add(self.lista_clientes, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND|wx.ALIGN_RIGHT, 10)
        sizer_7_copy.Add(self.btn_detalle_clientes, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy.Add(self.btn_eliminar_clientes, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7_copy.Add(self.btn_nuevo_clientes, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6_copy.Add(sizer_7_copy, 0, wx.RIGHT, 10)
        sizer_3_copy.Add(sizer_6_copy, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(sizer_3_copy)
        self.btn_detalle_prendas.AddPage(self.notebook_1_pane_1, "Prendas")
        self.btn_detalle_prendas.AddPage(self.notebook_1_pane_2, "Clientes")
        sizer_2.Add(self.btn_detalle_prendas, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
