#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Tue Apr 09 15:22:21 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class NuevoClienteFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NuevoClienteFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_nuevo_cliente = wx.StaticText(self.panel_1, -1, "NUEVO CLIENTE")
        self.label_dni = wx.StaticText(self.panel_1, -1, "DNI")
        self.texto_dni = wx.TextCtrl(self.panel_1, -1, "")
        self.label_nombre = wx.StaticText(self.panel_1, -1, "Nombre")
        self.texto_nombre = wx.TextCtrl(self.panel_1, -1, "")
        self.label_direccion = wx.StaticText(self.panel_1, -1, u"Dirección")
        self.texto_direccion = wx.TextCtrl(self.panel_1, -1, "")
        self.label_fecha_nacimiento = wx.StaticText(self.panel_1, -1, "Nacimiento")
        self.date_fecha_nacimiento = wx.DatePickerCtrl(self.panel_1, -1, style=wx.DP_DROPDOWN)
        self.label_telefono = wx.StaticText(self.panel_1, -1, "Telefono")
        self.texto_telefono = wx.TextCtrl(self.panel_1, -1, "")
        self.label_email = wx.StaticText(self.panel_1, -1, "e-mail")
        self.text_email = wx.TextCtrl(self.panel_1, -1, "")
        self.boton_cancelar = wx.Button(self.panel_1, -1, "Cancelar")
        self.boton_guardar = wx.Button(self.panel_1, -1, "Guardar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NuevoClienteFrame.__set_properties
        self.SetTitle("frame_1")
        self.label_nuevo_cliente.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_dni.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.texto_dni.SetMinSize((100, 25))
        self.texto_dni.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_nombre.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.texto_nombre.SetMinSize((195, 25))
        self.texto_nombre.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_direccion.SetMinSize((65, 19))
        self.label_direccion.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.texto_direccion.SetMinSize((330, 25))
        self.texto_direccion.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_fecha_nacimiento.SetMinSize((86, 19))
        self.label_fecha_nacimiento.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.date_fecha_nacimiento.SetMinSize((110, 19))
        self.date_fecha_nacimiento.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        self.label_telefono.SetMinSize((62, 19))
        self.label_telefono.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.texto_telefono.SetMinSize((333, 25))
        self.texto_telefono.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_email.SetMinSize((62, 19))
        self.label_email.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_email.SetMinSize((333, 25))
        self.text_email.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NuevoClienteFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_7 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3_copy_copy = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3_copy = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(1, 5, 0, 0)
        sizer_4.Add(self.label_nuevo_cliente, 0, wx.LEFT, 7)
        grid_sizer_2.Add(self.label_dni, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_2.Add(self.texto_dni, 0, wx.LEFT | wx.TOP, 8)
        grid_sizer_2.Add(self.label_nombre, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_2.Add(self.texto_nombre, 0, wx.LEFT | wx.TOP, 8)
        grid_sizer_2.AddGrowableCol(3)
        sizer_4.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_direccion, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_3.Add(self.texto_direccion, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 8)
        grid_sizer_3.AddGrowableCol(1)
        sizer_4.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_3_copy.Add(self.label_fecha_nacimiento, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_3_copy.Add(self.date_fecha_nacimiento, 0, wx.TOP, 10)
        grid_sizer_3_copy.AddGrowableCol(1)
        sizer_4.Add(grid_sizer_3_copy, 1, wx.EXPAND, 0)
        grid_sizer_3_copy_copy.Add(self.label_telefono, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_3_copy_copy.Add(self.texto_telefono, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 8)
        grid_sizer_3_copy_copy.AddGrowableCol(1)
        sizer_4.Add(grid_sizer_3_copy_copy, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(self.label_email, 0, wx.LEFT | wx.TOP, 10)
        grid_sizer_5.Add(self.text_email, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 8)
        sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_7.Add(self.boton_cancelar, 0, wx.ALL | wx.ALIGN_RIGHT, 4)
        grid_sizer_7.Add(self.boton_guardar, 0, wx.ALL, 4)
        grid_sizer_7.AddGrowableCol(0)
        sizer_4.Add(grid_sizer_7, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_4)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class NuevoClienteFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = NuevoClienteFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
