#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Mon Mar 18 16:40:23 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class FramePrincipal(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FramePrincipal.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.Prenda = wx.StaticText(self.panel_1, -1, "Prenda")
        self.label_1 = wx.StaticText(self.panel_1, -1, u"Código", style=wx.ALIGN_RIGHT)
        self.text_ctrl_1 = TextoCodigo(self.panel_1, -1, "")
        self.Nombre = wx.StaticText(self.panel_1, -1, "Nombre", style=wx.ALIGN_RIGHT)
        self.text_ctrl_2 = TextoNombre(self.panel_1, -1, "")
        self.Talle = wx.StaticText(self.panel_1, -1, "Talle", style=wx.ALIGN_RIGHT)
        self.text_ctrl_3 = TextoTalle(self.panel_1, -1, "")
        self.Talle_copy = wx.StaticText(self.panel_1, -1, "Costo", style=wx.ALIGN_RIGHT)
        self.text_ctrl_3_copy = TextoCosto(self.panel_1, -1, "")
        self.Talle_copy_1 = wx.StaticText(self.panel_1, -1, "Precio", style=wx.ALIGN_RIGHT)
        self.text_ctrl_3_copy_1 = TextoPrecio(self.panel_1, -1, "")
        self.label_1_copy = wx.StaticText(self.panel_1, -1, u"Descripción")
        self.text_ctrl_4 = TextoDescripcion(self.panel_1, -1, "", style=wx.TE_MULTILINE)
        self.Talle_copy_2 = wx.StaticText(self.panel_1, -1, "Vendida", style=wx.ALIGN_RIGHT)
        self.combo_box_1 = ComboVendido(self.panel_1, -1, choices=[u"Sí", "No"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.button_1 = BtnGuardar(self.panel_1, -1, "Guardar")
        self.button_2 = BtnCerrar(self.panel_1, -1, "Cerrar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FramePrincipal.__set_properties
        self.SetTitle("frame_1")
        self.Prenda.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.label_1.SetMinSize((53, 17))
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_1.SetMinSize((80, 26))
        self.Nombre.SetMinSize((53, 17))
        self.Nombre.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_2.SetMinSize((320, 26))
        self.Talle.SetMinSize((53, 17))
        self.Talle.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_3.SetMinSize((40, 26))
        self.Talle_copy.SetMinSize((50, 17))
        self.Talle_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_3_copy.SetMinSize((40, 26))
        self.Talle_copy_1.SetMinSize((53, 17))
        self.Talle_copy_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_3_copy_1.SetMinSize((40, 26))
        self.label_1_copy.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.text_ctrl_4.SetMinSize((400, 78))
        self.Talle_copy_2.SetMinSize((53, 17))
        self.Talle_copy_2.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Ubuntu"))
        self.combo_box_1.SetMinSize((80, 28))
        self.combo_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FramePrincipal.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.Prenda, 0, wx.LEFT | wx.TOP, 10)
        sizer_3.Add(self.label_1, 0, wx.LEFT | wx.TOP, 10)
        sizer_3.Add(self.text_ctrl_1, 0, wx.LEFT | wx.TOP, 6)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.Nombre, 0, wx.LEFT | wx.TOP, 10)
        sizer_4.Add(self.text_ctrl_2, 0, wx.LEFT | wx.TOP, 6)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.Talle, 0, wx.LEFT | wx.TOP, 10)
        sizer_5.Add(self.text_ctrl_3, 0, wx.LEFT | wx.TOP, 6)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.Talle_copy, 0, wx.LEFT | wx.TOP, 8)
        sizer_5_copy.Add(self.text_ctrl_3_copy, 0, wx.LEFT | wx.TOP, 6)
        sizer_6.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_5_copy_1.Add(self.Talle_copy_1, 0, wx.LEFT | wx.TOP, 10)
        sizer_5_copy_1.Add(self.text_ctrl_3_copy_1, 0, wx.LEFT | wx.TOP, 6)
        sizer_6.Add(sizer_5_copy_1, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_2.Add(self.label_1_copy, 0, wx.LEFT | wx.TOP, 10)
        sizer_2.Add(self.text_ctrl_4, 0, wx.ALL, 10)
        sizer_7.Add(self.Talle_copy_2, 0, wx.LEFT | wx.TOP, 10)
        sizer_7.Add(self.combo_box_1, 0, wx.LEFT | wx.TOP, 6)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.button_1, 0, 0, 0)
        sizer_8.Add(self.button_2, 0, 0, 0)
        sizer_2.Add(sizer_8, 1, wx.RIGHT | wx.BOTTOM | wx.ALIGN_RIGHT, 8)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.LEFT | wx.TOP, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class FramePrincipal
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = FramePrincipal(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
