#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Thu Mar 14 19:54:32 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class Carrito(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Carrito.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.labelCarrito = wx.StaticText(self.panel_2, -1, "Carrito")
        self.ListaCarrito = wx.ListCtrl(self.panel_2, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.BtnQuitar = wx.Button(self.panel_2, -1, "Quitar")
        self.BtnDescuento = wx.Button(self.panel_2, -1, "Descuento")
        self.LabelTotal = wx.StaticText(self.panel_2, -1, "Total", style=wx.ALIGN_RIGHT)
        self.TextoTotal = wx.TextCtrl(self.panel_2, -1, "")
        self.static_line_1 = wx.StaticLine(self.panel_2, -1)
        self.labelTipodeVenta = wx.StaticText(self.panel_2, -1, "Tipo de Venta")
        self.notebook_1 = wx.Notebook(self.panel_2, -1, style=0)
        self.PanelCasual = wx.Panel(self.notebook_1, -1)
        self.LabelTotalP = wx.StaticText(self.PanelCasual, -1, "Total")
        self.TextoTotalC = wx.TextCtrl(self.PanelCasual, -1, "")
        self.LabelPagarP = wx.StaticText(self.PanelCasual, -1, "Pagar con")
        self.TextoPagarC = wx.TextCtrl(self.PanelCasual, -1, "")
        self.label_3 = wx.StaticText(self.PanelCasual, -1, "Vuelto")
        self.TextoVueltoC = wx.TextCtrl(self.PanelCasual, -1, "")
        self.PanelCliente = wx.Panel(self.notebook_1, -1)
        self.TextoBuscar = wx.TextCtrl(self.PanelCliente, -1, "Buscar...", style=wx.TE_CENTRE)
        self.radio_btn_1 = wx.RadioButton(self.PanelCliente, -1, "DNI")
        self.radio_btn_2 = wx.RadioButton(self.PanelCliente, -1, "Nombre")
        self.ListaCliente = wx.ListCtrl(self.PanelCliente, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
        self.Condicional = wx.CheckBox(self.PanelCliente, -1, "Condicional")
        self.LabelTotalP_copy = wx.StaticText(self.PanelCliente, -1, "Total")
        self.TextoTotalC_c = wx.TextCtrl(self.PanelCliente, -1, "")
        self.LabelPagarP_copy = wx.StaticText(self.PanelCliente, -1, "Pagar con")
        self.TextoPagarC_c = wx.TextCtrl(self.PanelCliente, -1, "")
        self.label_3_copy = wx.StaticText(self.PanelCliente, -1, "Vuelto")
        self.TextoVueltoC_c = wx.TextCtrl(self.PanelCliente, -1, "")
        self.BtnCancelar = wx.Button(self.panel_2, -1, "Cancelar")
        self.BtnImprimir = wx.Button(self.panel_2, -1, "Imprimir")
        self.BtnAceptar = wx.Button(self.panel_2, -1, "Aceptar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Carrito.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((683, 649))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Carrito.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_9_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.labelCarrito, 0, wx.TOP, 20)
        sizer_4.Add(self.ListaCarrito, 1, wx.BOTTOM | wx.EXPAND, 50)
        sizer_5.Add(self.BtnQuitar, 0, 0, 0)
        sizer_5.Add((20, 50), 0, 0, 0)
        sizer_5.Add(self.BtnDescuento, 0, 0, 0)
        sizer_4.Add(sizer_5, 0, wx.LEFT | wx.RIGHT | wx.BOTTOM | wx.ALIGN_CENTER_VERTICAL, 45)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_6.Add(self.LabelTotal, 1, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 390)
        sizer_6.Add(self.TextoTotal, 0, wx.RIGHT, 180)
        sizer_3.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_3.Add(self.static_line_1, 0, wx.TOP | wx.EXPAND, 45)
        sizer_3.Add(self.labelTipodeVenta, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_9.Add(self.LabelTotalP, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(self.TextoTotalC, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(self.LabelPagarP, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_9.Add(self.TextoPagarC, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(self.label_3, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_9.Add(self.TextoVueltoC, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.PanelCasual.SetSizer(sizer_9)
        sizer_11.Add(self.TextoBuscar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_11.Add(self.radio_btn_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_11.Add(self.radio_btn_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_10.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_14.Add(self.ListaCliente, 1, wx.EXPAND, 0)
        sizer_14.Add(self.Condicional, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_10.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_9_copy.Add(self.LabelTotalP_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9_copy.Add(self.TextoTotalC_c, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9_copy.Add(self.LabelPagarP_copy, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_9_copy.Add(self.TextoPagarC_c, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9_copy.Add(self.label_3_copy, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_9_copy.Add(self.TextoVueltoC_c, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_10.Add(sizer_9_copy, 0, wx.EXPAND, 0)
        self.PanelCliente.SetSizer(sizer_10)
        self.notebook_1.AddPage(self.PanelCasual, "Casual")
        self.notebook_1.AddPage(self.PanelCliente, "Cliente")
        sizer_7.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_13.Add(self.BtnCancelar, 0, 0, 0)
        sizer_13.Add(self.BtnImprimir, 0, 0, 0)
        sizer_13.Add(self.BtnAceptar, 0, 0, 0)
        sizer_7.Add(sizer_13, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(sizer_7, 0, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_2)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class Carrito
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_Carrito = Carrito(None, -1, "")
    app.SetTopWindow(frame_Carrito)
    frame_Carrito.Show()
    app.MainLoop()
